config/routes.rb
Dartsight::Application.routes.draw do
  
  match '/device', :to => 'pages#device'
  
  match '/method', :to => 'pages#method'
  
  match '/buy', :to => 'pages#buy'
  
  match '/contact', :to => 'pages#contact'
  
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def device
    @title = "Device"
  end

  def method
    @title = "Method"
  end

  def buy
    @title = "Buy"
  end
  
  def contact
    @title = "Contact"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return a title on a per-page basis
  def title
    base_title = "DartSight"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  #Set the logo
  def logo
    image_tag("dartsight_logo2.png", :alt => "Dartsight Logo", :class => "round", :width => "250px")
  end
  
  #Set the Buttons
  def buyButton
    image_tag("buyButton.png", :alt => "Buy DartSight", :class => "round", :width => "225px")
  end
  
  def twitterButton
    image_tag("twitterButton.png", :alt => "Twitter", :class => "round", :height => "30px")
  end
  
  def facebookButton
    image_tag("facebookButton.png", :alt => "Facebook", :class => "round", :height => "30px")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <hr />
    <div class="span-14">
        &copy; 2012 DartSight | Questions? Email us at <a href="mailto:questions@dartsight.com">questions@dartsight.com</a>.
    </div>
    <div class="span-10 last">
        <ul class="footnav">
            <li><%= link_to_unless_current "Home", root_path %></li>
            <li><%= link_to_unless_current "Device", device_path %></li>
            <li><%= link_to_unless_current "Method", method_path %></li>
            <li><%= link_to_unless_current "Buy", buy_path %></li>
        </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="span-14" id="logo">
        <%= link_to_unless_current logo, root_path %>
    </div>
    <nav class="span-10 last">
      <ul>
        <li><%= link_to_unless_current "Home", root_path %></li>
        <li><%= link_to_unless_current "Device", device_path %></li>
        <li><%= link_to_unless_current "Method", method_path %></li>
        <li><%= link_to_unless_current "Buy", buy_path %></li>
      </ul>
    </nav>
</header>

app/views/layouts/_tweets.html.erb
<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 3,
  interval: 30000,
  width: 225,
  height: 300,
  theme: {
    shell: {
      background: '#114411',
      color: '#ffffff'
    },
    tweets: {
      background: '#ffffff',
      color: '#000000',
      links: '#c50202'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: false,
    behavior: 'all'
  }
}).render().setUser('DartSight').start();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= stylesheet_link_tag 'custom' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- [if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
</head>
  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="header">
      <div class="container">
        <%= render "layouts/header" %>
      </div>
    </div>
    <hr />
    <div class="container main">
      <section class="round span-24 last">
        <div class="span-16 colborder">
          <%= yield %>
        </div>
        <div class="span-7 last rightBar">
          <%= render "layouts/tweets" %>
          <br />
          <div id="buyButton">
          <%= link_to_unless_current buyButton, buy_path, :class => "shadow" %>
          </div>
          <div class="follow">
            Follow us for updates:
            <%= link_to twitterButton, "http://twitter.com/DartSight" %>
            <%= link_to facebookButton, "http://facebook.com/DartSight" %>
        </div>
      </section>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/pages/buy.html.erb
<%= image_tag("paypal", :width => "500px") %>
<hr />
<p>If you would like discuss options for purchasing DartSight in bulk, please contact us at <a href="mailto:sales@dartsight.com">sales@dartsight.com</a>.

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/device.html.erb
<div class="span-8 imageLeft">
  <%= image_tag("device.png", :alt => "DartSight", :width => "300px") %>
</div>
<div class="span-7 last">
  <h1>Training with DartSight</h1>
  <p class="summary">
    With the adjustable DartSight training tool, you start every throw with the dart exactly where it needs to be to fit your throw. DartSight&rsquo;s circular sighter allows you to keep an eye on your target while you make sure it is directly in your line of fire.
  </p>
</div>
<hr />
<div class="span-15 last">
  <%= image_tag("handscut.png", :alt => "Saccades", :width => "200px", :class => "floatRight") %>
  <h5>
    Perfect Practice Makes Perfect
  </h5>
  <p>
    According to common wisdom, practice makes perfect. The truth is that only perfect practice makes perfect.
  </p>
  <ul>
    <li>Start every throw with the dart in the same location relative to your target.</li>
    <li>Keep the dart on line with your target throughout your throwing motion.</li>
    <li>Build a reproducible rhythm.</li>
    <li>Hit your spots consistently.</li>
  </ul>
  <p>
    

</div>

app/views/pages/home.html.erb
<div class="span-8 imageLeft">
  <%= image_tag("trophy.jpg", :alt => "David with Trophy", :width => "300px") %>
</div>
<div class="span-7 last">
  <h2>This is DartSight.</h2>
  <p class="summary">
    Modern sport is infused with science. Top athletes gain advantages by taking the guesswork out of their craft. Now darts has caught up.
  </p>
  <p class="summary">
    DartSight is the revolutionary training tool that changes the way the game is played.
  </p>
</div>
<hr />
<div class="span-5">
  <h3>The DartSight Way</h3>
    <p class="text">
      DartSight makes sense of darts. Using the DartSight method will produce consistently accurate results. And in darts, consistency is king.
    </p>
    <h4 class="text">Watch the video:</h4>  
</div>
<div class="span-10 last video">
  <iframe class="shadow" width="400" height="233" src="http://www.youtube.com/embed/Z1_uAPuVikM?rel=0" frameborder="0" allowfullscreen></iframe>
</div>

app/views/pages/method.html.erb
<div class="span-8 imageLeft">
  <%= image_tag("davidsight.png", :alt => "David with DartSight", :width => "300px") %>
</div>
<div class="span-7 last">
  <h1>BrainWorks for Darts</h1>
  <p class="summary">
    The DartSight method applies advanced research on two innate brain processes to the art of darts. DartSight works with your brain to improve your game.
  </p>
</div>
<hr />
<div class="span-15 last">
  <%= image_tag("saccades.png", :alt => "Saccades", :width => "250px", :class => "floatRight") %>
  <h5>
    Saccadic Darts
  </h5>
  <p>
    Saccades are quick, simultaneous movements of both eyes in the same direction used to quickly scan a scene. The brain achieves its highest level of focus immediately after these movements, which typically cover an angle of 2-4 degrees.
  </p>
  <h5>
    Blinking Darts
  </h5>
  <p>
    Blinking is the mind's way of punctuating thought. The human brain uses the blink to clear itself in preparation for a new task. 
  </p>
</div>
<div class="span-15 last">
  <p>
    Used in combination, blinking and saccades allow you to throw your best darts. To hit a number in the triple ring, focus on the bullseye, blink, shift to your target, and throw. Combining the proper technique that DartSight teaches with the Blink-Shift-Throw rhythm is the fastest and most effective way to internalize a solid, repeatable, and accurate motion.
  </p>
</div>